//
// Parallel Prefix Tree - KOGGE-STONE
// Width: 8 bits
// Levels: 3
// Pipeline stages: 0
// Auto-generated by prefix_tree.py
//

module prefix_tree #(
    parameter WIDTH = 8,
    parameter PIPE = 0
) (
    input  logic clk,
    input  logic rst,
    input  logic [WIDTH-1:0] g_in,  // Generate inputs
    input  logic [WIDTH-1:0] p_in,  // Propagate inputs
    input  logic [WIDTH-1:0] a_in,  // Auxiliary inputs
    output logic [WIDTH-1:0] g_out, // Generate outputs (prefix)
    output logic [WIDTH-1:0] p_out, // Propagate outputs
    output logic [WIDTH-1:0] a_out  // Auxiliary outputs
);

    // Prefix tree stages (number of levels)
    parameter PREFIX_STAGES = 3;

    // Level 0 signals
    logic [WIDTH-1:0] g_L0;
    logic [WIDTH-1:0] p_L0;
    logic [WIDTH-1:0] a_L0;

    // Level 1 signals
    logic [WIDTH-1:0] g_L1;
    logic [WIDTH-1:0] p_L1;
    logic [WIDTH-1:0] a_L1;

    // Level 2 signals
    logic [WIDTH-1:0] g_L2;
    logic [WIDTH-1:0] p_L2;
    logic [WIDTH-1:0] a_L2;

    // Level 3 signals
    logic [WIDTH-1:0] g_L3;
    logic [WIDTH-1:0] p_L3;
    logic [WIDTH-1:0] a_L3;

    // Connect inputs to level 0
    assign g_L0 = g_in;
    assign p_L0 = p_in;
    assign a_L0 = a_in;

    // Level 1 prefix cells
    prefix_cell #(.PIPE(PIPE)) cell_L1_0 (
        .clk(clk),
        .rst(rst),
        .g_hi(g_L0[0]),
        .p_hi(p_L0[0]),
        .a_hi(a_L0[0]),
        .g_lo(1'b0),  // Identity: g_out = g_hi
        .p_lo(1'b1),  // Identity: p_out = p_hi
        .a_lo(1'b0),  // Identity: a_out = a_hi
        .g_out(g_L1[0]),
        .p_out(p_L1[0]),
        .a_out(a_L1[0])
    );
    prefix_cell #(.PIPE(PIPE)) cell_L1_1 (
        .clk(clk),
        .rst(rst),
        .g_hi(g_L0[1]),
        .p_hi(p_L0[1]),
        .a_hi(a_L0[1]),
        .g_lo(g_L0[0]),
        .p_lo(p_L0[0]),
        .a_lo(a_L0[0]),
        .g_out(g_L1[1]),
        .p_out(p_L1[1]),
        .a_out(a_L1[1])
    );
    prefix_cell #(.PIPE(PIPE)) cell_L1_2 (
        .clk(clk),
        .rst(rst),
        .g_hi(g_L0[2]),
        .p_hi(p_L0[2]),
        .a_hi(a_L0[2]),
        .g_lo(g_L0[1]),
        .p_lo(p_L0[1]),
        .a_lo(a_L0[1]),
        .g_out(g_L1[2]),
        .p_out(p_L1[2]),
        .a_out(a_L1[2])
    );
    prefix_cell #(.PIPE(PIPE)) cell_L1_3 (
        .clk(clk),
        .rst(rst),
        .g_hi(g_L0[3]),
        .p_hi(p_L0[3]),
        .a_hi(a_L0[3]),
        .g_lo(g_L0[2]),
        .p_lo(p_L0[2]),
        .a_lo(a_L0[2]),
        .g_out(g_L1[3]),
        .p_out(p_L1[3]),
        .a_out(a_L1[3])
    );
    prefix_cell #(.PIPE(PIPE)) cell_L1_4 (
        .clk(clk),
        .rst(rst),
        .g_hi(g_L0[4]),
        .p_hi(p_L0[4]),
        .a_hi(a_L0[4]),
        .g_lo(g_L0[3]),
        .p_lo(p_L0[3]),
        .a_lo(a_L0[3]),
        .g_out(g_L1[4]),
        .p_out(p_L1[4]),
        .a_out(a_L1[4])
    );
    prefix_cell #(.PIPE(PIPE)) cell_L1_5 (
        .clk(clk),
        .rst(rst),
        .g_hi(g_L0[5]),
        .p_hi(p_L0[5]),
        .a_hi(a_L0[5]),
        .g_lo(g_L0[4]),
        .p_lo(p_L0[4]),
        .a_lo(a_L0[4]),
        .g_out(g_L1[5]),
        .p_out(p_L1[5]),
        .a_out(a_L1[5])
    );
    prefix_cell #(.PIPE(PIPE)) cell_L1_6 (
        .clk(clk),
        .rst(rst),
        .g_hi(g_L0[6]),
        .p_hi(p_L0[6]),
        .a_hi(a_L0[6]),
        .g_lo(g_L0[5]),
        .p_lo(p_L0[5]),
        .a_lo(a_L0[5]),
        .g_out(g_L1[6]),
        .p_out(p_L1[6]),
        .a_out(a_L1[6])
    );
    prefix_cell #(.PIPE(PIPE)) cell_L1_7 (
        .clk(clk),
        .rst(rst),
        .g_hi(g_L0[7]),
        .p_hi(p_L0[7]),
        .a_hi(a_L0[7]),
        .g_lo(g_L0[6]),
        .p_lo(p_L0[6]),
        .a_lo(a_L0[6]),
        .g_out(g_L1[7]),
        .p_out(p_L1[7]),
        .a_out(a_L1[7])
    );

    // Level 2 prefix cells
    prefix_cell #(.PIPE(PIPE)) cell_L2_0 (
        .clk(clk),
        .rst(rst),
        .g_hi(g_L1[0]),
        .p_hi(p_L1[0]),
        .a_hi(a_L1[0]),
        .g_lo(1'b0),  // Identity: g_out = g_hi
        .p_lo(1'b1),  // Identity: p_out = p_hi
        .a_lo(1'b0),  // Identity: a_out = a_hi
        .g_out(g_L2[0]),
        .p_out(p_L2[0]),
        .a_out(a_L2[0])
    );
    prefix_cell #(.PIPE(PIPE)) cell_L2_1 (
        .clk(clk),
        .rst(rst),
        .g_hi(g_L1[1]),
        .p_hi(p_L1[1]),
        .a_hi(a_L1[1]),
        .g_lo(1'b0),  // Identity: g_out = g_hi
        .p_lo(1'b1),  // Identity: p_out = p_hi
        .a_lo(1'b0),  // Identity: a_out = a_hi
        .g_out(g_L2[1]),
        .p_out(p_L2[1]),
        .a_out(a_L2[1])
    );
    prefix_cell #(.PIPE(PIPE)) cell_L2_2 (
        .clk(clk),
        .rst(rst),
        .g_hi(g_L1[2]),
        .p_hi(p_L1[2]),
        .a_hi(a_L1[2]),
        .g_lo(g_L1[0]),
        .p_lo(p_L1[0]),
        .a_lo(a_L1[0]),
        .g_out(g_L2[2]),
        .p_out(p_L2[2]),
        .a_out(a_L2[2])
    );
    prefix_cell #(.PIPE(PIPE)) cell_L2_3 (
        .clk(clk),
        .rst(rst),
        .g_hi(g_L1[3]),
        .p_hi(p_L1[3]),
        .a_hi(a_L1[3]),
        .g_lo(g_L1[1]),
        .p_lo(p_L1[1]),
        .a_lo(a_L1[1]),
        .g_out(g_L2[3]),
        .p_out(p_L2[3]),
        .a_out(a_L2[3])
    );
    prefix_cell #(.PIPE(PIPE)) cell_L2_4 (
        .clk(clk),
        .rst(rst),
        .g_hi(g_L1[4]),
        .p_hi(p_L1[4]),
        .a_hi(a_L1[4]),
        .g_lo(g_L1[2]),
        .p_lo(p_L1[2]),
        .a_lo(a_L1[2]),
        .g_out(g_L2[4]),
        .p_out(p_L2[4]),
        .a_out(a_L2[4])
    );
    prefix_cell #(.PIPE(PIPE)) cell_L2_5 (
        .clk(clk),
        .rst(rst),
        .g_hi(g_L1[5]),
        .p_hi(p_L1[5]),
        .a_hi(a_L1[5]),
        .g_lo(g_L1[3]),
        .p_lo(p_L1[3]),
        .a_lo(a_L1[3]),
        .g_out(g_L2[5]),
        .p_out(p_L2[5]),
        .a_out(a_L2[5])
    );
    prefix_cell #(.PIPE(PIPE)) cell_L2_6 (
        .clk(clk),
        .rst(rst),
        .g_hi(g_L1[6]),
        .p_hi(p_L1[6]),
        .a_hi(a_L1[6]),
        .g_lo(g_L1[4]),
        .p_lo(p_L1[4]),
        .a_lo(a_L1[4]),
        .g_out(g_L2[6]),
        .p_out(p_L2[6]),
        .a_out(a_L2[6])
    );
    prefix_cell #(.PIPE(PIPE)) cell_L2_7 (
        .clk(clk),
        .rst(rst),
        .g_hi(g_L1[7]),
        .p_hi(p_L1[7]),
        .a_hi(a_L1[7]),
        .g_lo(g_L1[5]),
        .p_lo(p_L1[5]),
        .a_lo(a_L1[5]),
        .g_out(g_L2[7]),
        .p_out(p_L2[7]),
        .a_out(a_L2[7])
    );

    // Level 3 prefix cells
    prefix_cell #(.PIPE(PIPE)) cell_L3_0 (
        .clk(clk),
        .rst(rst),
        .g_hi(g_L2[0]),
        .p_hi(p_L2[0]),
        .a_hi(a_L2[0]),
        .g_lo(1'b0),  // Identity: g_out = g_hi
        .p_lo(1'b1),  // Identity: p_out = p_hi
        .a_lo(1'b0),  // Identity: a_out = a_hi
        .g_out(g_L3[0]),
        .p_out(p_L3[0]),
        .a_out(a_L3[0])
    );
    prefix_cell #(.PIPE(PIPE)) cell_L3_1 (
        .clk(clk),
        .rst(rst),
        .g_hi(g_L2[1]),
        .p_hi(p_L2[1]),
        .a_hi(a_L2[1]),
        .g_lo(1'b0),  // Identity: g_out = g_hi
        .p_lo(1'b1),  // Identity: p_out = p_hi
        .a_lo(1'b0),  // Identity: a_out = a_hi
        .g_out(g_L3[1]),
        .p_out(p_L3[1]),
        .a_out(a_L3[1])
    );
    prefix_cell #(.PIPE(PIPE)) cell_L3_2 (
        .clk(clk),
        .rst(rst),
        .g_hi(g_L2[2]),
        .p_hi(p_L2[2]),
        .a_hi(a_L2[2]),
        .g_lo(1'b0),  // Identity: g_out = g_hi
        .p_lo(1'b1),  // Identity: p_out = p_hi
        .a_lo(1'b0),  // Identity: a_out = a_hi
        .g_out(g_L3[2]),
        .p_out(p_L3[2]),
        .a_out(a_L3[2])
    );
    prefix_cell #(.PIPE(PIPE)) cell_L3_3 (
        .clk(clk),
        .rst(rst),
        .g_hi(g_L2[3]),
        .p_hi(p_L2[3]),
        .a_hi(a_L2[3]),
        .g_lo(1'b0),  // Identity: g_out = g_hi
        .p_lo(1'b1),  // Identity: p_out = p_hi
        .a_lo(1'b0),  // Identity: a_out = a_hi
        .g_out(g_L3[3]),
        .p_out(p_L3[3]),
        .a_out(a_L3[3])
    );
    prefix_cell #(.PIPE(PIPE)) cell_L3_4 (
        .clk(clk),
        .rst(rst),
        .g_hi(g_L2[4]),
        .p_hi(p_L2[4]),
        .a_hi(a_L2[4]),
        .g_lo(g_L2[0]),
        .p_lo(p_L2[0]),
        .a_lo(a_L2[0]),
        .g_out(g_L3[4]),
        .p_out(p_L3[4]),
        .a_out(a_L3[4])
    );
    prefix_cell #(.PIPE(PIPE)) cell_L3_5 (
        .clk(clk),
        .rst(rst),
        .g_hi(g_L2[5]),
        .p_hi(p_L2[5]),
        .a_hi(a_L2[5]),
        .g_lo(g_L2[1]),
        .p_lo(p_L2[1]),
        .a_lo(a_L2[1]),
        .g_out(g_L3[5]),
        .p_out(p_L3[5]),
        .a_out(a_L3[5])
    );
    prefix_cell #(.PIPE(PIPE)) cell_L3_6 (
        .clk(clk),
        .rst(rst),
        .g_hi(g_L2[6]),
        .p_hi(p_L2[6]),
        .a_hi(a_L2[6]),
        .g_lo(g_L2[2]),
        .p_lo(p_L2[2]),
        .a_lo(a_L2[2]),
        .g_out(g_L3[6]),
        .p_out(p_L3[6]),
        .a_out(a_L3[6])
    );
    prefix_cell #(.PIPE(PIPE)) cell_L3_7 (
        .clk(clk),
        .rst(rst),
        .g_hi(g_L2[7]),
        .p_hi(p_L2[7]),
        .a_hi(a_L2[7]),
        .g_lo(g_L2[3]),
        .p_lo(p_L2[3]),
        .a_lo(a_L2[3]),
        .g_out(g_L3[7]),
        .p_out(p_L3[7]),
        .a_out(a_L3[7])
    );

    // Connect outputs from final level
    assign g_out = g_L3;
    assign p_out = p_L3;
    assign a_out = a_L3;

endmodule
