//
// Parallel Prefix Tree - KOGGE-STONE
// Width: 8
// Pipeline stages: 0
// Auto-generated by prefix_tree.py
//

module prefix_tree #(
    parameter bit PIPE = 0
) (
    input  logic clk,
    input  logic rst,
    input  logic g_hi,  // Generate high (MSB)
    input  logic p_hi,  // Propagate high (MSB)
    input  logic a_hi,  // Auxiliary high (MSB)
    input  logic g_lo,  // Generate low (LSB)
    input  logic p_lo,  // Propagate low (LSB)
    input  logic a_lo,  // Auxiliary low (LSB)
    output logic g_out, // Group generate
    output logic p_out, // Group propagate
    output logic a_out  // Auxiliary output
);

    // Combinational prefix cell
    assign g_out = g_hi | (p_hi & g_lo);
    assign p_out = p_hi & p_lo;
    assign a_out = a_hi | (p_hi & a_lo);

endmodule
