source /CMC/scripts/synopsis.syn.2023.12-SP2.csh
source /CMC/scripts/cadence.innovus21.17.000.csh
source /CMC/scripts/synopsis.lc.2019.12-SP2.csh
source /CMC/scripts/synopsis.pts.2019.03-SP3.csh
source /CMC/scripts/mentor.modelsim.10.7c.csh
source /CMC/scripts/cadence.genus21.17.000.csh

cp -p /CMC/kits/tsmc_65nm/CRN65GP/PDK_OA/display.drf ./display.drf

setenv CMC_CDS_IC_HOME /CMC/tools/cadence/IC23.10.050_lnx86/tools/
echo "# Do not modify." > tech.lib
echo "# This file is autogenerated by the environment setup script." >> tech.lib
echo "DEFINE sbaLib ${CMC_CDS_IC_HOME}/tools/dfII/etc/cdslib/artist/sbaLib" >> tech.lib
echo "DEFINE sample ${CMC_CDS_IC_HOME}/tools/dfII/samples/cdslib/sample" >> tech.lib
echo "INCLUDE /CMC/kits/tsmc_65nm/CRN65GP/PDK_OA/cds.lib" >> tech.lib

echo "DEFINE tcbn65gplus /CMC/kits/tsmc_65nm_libs/tcbn65gplus_200a/TSMCHOME/digital/Back_End/cdk_OA/tcbn65gplus" >> tech.lib
echo "DEFINE tpan65gpgv2od3 /CMC/kits/tsmc_65nm_libs/tpan65gpgv2od3_200b/TSMCHOME/digital/Back_End/cdk_OA/tpan65gpgv2od3" >> tech.lib
echo "DEFINE tpfn65gpgv2od3 /CMC/kits/tsmc_65nm_libs/tpfn65gpgv2od3_200c/TSMCHOME/digital/Back_End/cdk_OA/tpfn65gpgv2od3" >> tech.lib
echo "DEFINE tpbn65v /CMC/kits/tsmc_65nm_libs/tpbn65v_200b/TSMCHOME/digital/Back_End/cdk_OA/tpbn65v" >> tech.lib
